mp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from mimetypes import *
import os
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models import Max



# Create your models here.
class profile(models.Model):
    dp = models.ImageField(upload_to='dp', null=True, verbose_name='dp',default="/static/img/avatar7.png", blank = True, unique = True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    bio = models.TextField(max_length=150, verbose_name='bio', null=True, blank=False)
    def __str__(self):
        return str(self.user)

class Post(models.Model):
    description = models.CharField(max_length=255, blank=True)
    file = models.FileField(upload_to = "post", null=False, default="")
    user_name = models.ForeignKey(User, on_delete=models.CASCADE)
    p_dp = models.ImageField(upload_to='dp', null=True,default="/static/img/avatar8.png", blank = True)
    tags = models.CharField(max_length=100, blank=True)
    post_time = models.DateTimeField(default=timezone.now)
    likes = models.IntegerField(default=0)
    comnt = models.IntegerField(default=0)
    
    def __str__(self):
        return str(self.user_name)
    
    def file_type(self):
        name, extension = os.path.splitext(self.file.name)
        if extension == '.jpg':
            return 'jpg'
        elif extension == '.JPG':
            return 'JPG'
        elif extension == '.jpeg':
            return 'jpeg'
        elif extension == '.JPEG':
            return 'JPEG'
        elif extension == '.mp4':
            return 'mp4'
        elif extension == '.MP4':
            return 'MP4'
        

class Likes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_like')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_likes')
    

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    date = models.DateTimeField(default=timezone.now)

class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver', default=None)
    message = models.CharField(max_length=1200, default="")
    timestamp = models.DateTimeField(default=timezone.now)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.message

    class Meta:
        ordering = ('timestamp',)

app/templates/about.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
<link rel="icon" type="image/x-icon" href="{% static 'img/Snapify (3).png' %}">
<title>Home - Snapify</title>
<meta name="description" content="Photo and video sharing app">
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="https://maxcdn.icons8.com/fonts/line-awesome/1.1/css/line-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css">
<link rel="stylesheet" href="{% static 'fonts/fontawesome5-overrides.min.css' %}">
<link rel="stylesheet" href="{% static 'css/styles.min.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.css">
</head>
<body id="page-top" data-bs-spy="scroll" data-bs-target="#mainNav" data-bs-offset="56">
<nav class="navbar navbar-light navbar-expand-lg fixed-top" id="mainNav">
<div class="container">
{% if user.is_authenticated %}<a href="/">{% endif %}<img src="{% static 'img/Snapify (1).png' %}" style="width: 150px;height: 55px;" /></a>
<button data-bs-toggle="collapse" data-bs-target="#navbarResponsive" class="navbar-toggler float-end" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
<i class="fa fa-bars"></i>
</button>
<div class="collapse navbar-collapse" id="navbarResponsive">
<ul class="navbar-nav ms-auto">
<li class="nav-item"><a class="nav-link" href="#download">Download</a></li>
<li class="nav-item"><a class="nav-link" href="#features">Features</a></li>
<li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
{% if not user.is_authenticated %}
<li class="nav-item"><a class="btn btn-light action-button" role="button" href="/signin" style="height: 29px;background: var(--bs-blue);margin-top: 0px;border-style: none;margin-left: 2px;">Login</a></li>
<li class="nav-item"><a class="btn btn-light action-button" role="button" href="/signup" style="height: 29px;background: #f4476b;margin-top: 0px;border-style: none;margin-left: 2px;">Signup</a></li>
{% endif %}
</ul>
</div>
</div>
</nav>
<header class="masthead" style="background: url('{% static 'img/bg-pattern.png' %}'), linear-gradient(to left, #7b4397, #dc2430);">
<div class="container h-100">
<div class="row h-100" style="margin: -5px;width: 1366px;">
<div class="col-lg-7 my-auto">
<div class="mx-auto header-content">
<h1 class="mb-5">Snapify give people the power to build community and bring the world closer together</h1>
{% if not user.is_authenticated %}
<a class="btn btn-outline-warning btn-xl" role="button" href="/signup">Start Now for Free!</a>
{% endif %}
</div>
</div>
<div class="col-lg-5 my-auto" style="width: 400px;height: 631.713px;">
<div class="device-container">
<div class="device-mockup iphone6_plus portrait white">
<div class="device" style="background-image:url({% static 'img/iphone_6_plus_white_port.png' %});">
<div class="screen"><img src="{% static 'img/Snapify (2).png' %}" style="width: 290px;height: 511px;transform: scale(1.03);"></div>
</div>
</div>
</div>
<div class="iphone-mockup"></div>
</div>
</div>
</div>
</header>
<section class="text-center bg-primary download" id="download">
<div class="container">
<div class="row">
<div class="col-md-8 mx-auto">
<h2 class="section-heading">Discover what all the buzz is about!</h2>
<p>Our app is available on any mobile device! Download now to get started!</p>
<div class="badges"><a class="badge-link" href="#"><img src="{% static 'img/google-play-badge.svg' %}"></a>
<a class="badge-link" href="#"><img src="{% static 'img/app-store-badge.svg' %}"></a>
</div>
</div>
</div>
</div>
</section>
<section id="features" class="features">
<div class="container">
<div class="text-center section-heading">
<h2>Unlimited Features, Unlimited Fun</h2>
<p class="text-muted">Check out what you can do with this App!</p>
<hr>
</div>
<div class="row">
<div class="col-lg-4 my-auto">
<div class="device-container">
<div class="device-mockup iphone6_plus portrait white">
<div class="device" style="background-image:url({% static 'img/iphone_6_plus_white_port.png' %});">
<div class="screen">
<img class="img-fluid" src="{% static 'img/demo-screen-1.jpg' %}">
</div></div></div></div></div>
<div class="col-lg-8 my-auto">
<div class="container-fluid">
<div class="row">
<div class="col-lg-6">
<div class="feature-item">
<i class="icon-screen-desktop text-primary"></i>
<h3>Device Mockups</h3>
<p class="text-muted">You can post an image, video!</p>
</div></div>
<div class="col-lg-6">
<div class="feature-item">
<i class="icon-globe text-primary"></i>
<h3>Flexible Use</h3>
<p class="text-muted">Internet has no boundary, So you can use it anywhere in the world!</p>
</div></div>
<div class="col-lg-6">
<div class="feature-item">
<i class="icon-present text-primary"></i>
<h3>Free to Use</h3>
<p class="text-muted">Snapify is totally free to use, So stay connected to world!</p>
</div></div>
<div class="col-lg-6">
<div class="feature-item">
<i class="icon-lock-open text-primary"></i>
<h3>Open Source</h3>
<p class="text-muted">Snapify is available on github, you can experiment for personal fun.</p>
</div></div></div></div></div></div></div>
</section>
<section class="cta" style="background-image:url({% static 'img/bg-cta.jpg' %});">
<div class="cta-content">
<div class="container">
<h2>Stop waiting.<br> Start Posting.</h2>
{% if not user.is_authenticated %}
<a class="btn btn-outline-warning btn-xl" role="button" href="/signup">Let's Get Started!</a>
{% endif %}
</div></div>
<div class="overlay"></div>
</section>
<section class="bg-primary contact" id="contact">
<div class="container">
<h2><span>We&nbsp;</span><i class="fa fa-heart"></i><span>&nbsp;new friends!</span></h2>
<ul class="list-inline list-social">
<li class="list-inline-item social-twitter"><a href="#"><i class="fa fa-twitter"></i></a></li>
<li class="list-inline-item social-facebook"><a href="#"><i class="fa fa-facebook"></i></a></li>
<li class="list-inline-item social-google-plus"><a href="#"><i class="fa fa-google-plus"></i></a></li>
</ul>
</div>
</section>
<footer>
<div class="container">
<p>©&nbsp;Snapify 2021. All Rights Reserved.</p>
<ul class="list-inline">
<li class="list-inline-item"><a href="#">Privacy</a></li>
<li class="list-inline-item"><a href="#">Terms</a></li>
<li class="list-inline-item"><a href="#">FAQ</a></li>
</ul>
</div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.js"></script>
<script src="{% static 'js/script.min.js' %}"></script>

</body>
</html>

app/templates/direct.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static 'img/Snapify (3).png' %}">
    <title>minor</title>
    <meta name="description" content="Photo and video sharing app">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://maxcdn.icons8.com/fonts/line-awesome/1.1/css/line-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome5-overrides.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.css">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" href="{% static 'css/message.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
</head>

<body>
    <nav class="navbar navbar-light navbar-expand-lg fixed-top shadow-sm" id="mainNav" style="border-color: transparent;border-bottom-color: var(--bs-red);background: var(--bs-light);">
        <div class="container"><a href="/"><img src="{% static 'img/Snapify (1).png' %}" style="width: 150px;height: 55px;" /></a>
            <div class="d-xxl-flex align-items-xxl-center" style="margin: 0px;padding: 0px;margin-right: 0px;transform: scale(0.80);"><a href="/" style=""><i class="la la-home d-xxl-flex align-items-xxl-center" style="margin-right: 100px;transform: scale(2.80);padding: 0px;"></a></i><i class="fab fa-facebook-messenger d-xxl-flex align-items-xxl-center" style="margin-right: 100px;transform: scale(2);"></i><a href="/post"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-plus-square d-xxl-flex align-items-xxl-center" style="margin-right: 100px;transform: scale(2);width: 17px;height: 30px;">
                    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"></path>
                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"></path>
                </svg></a>
                <div class="dropdown" style="margin-right: 50px">
                  <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                   <img class="border rounded-circle d-xxl-flex align-items-xxl-center" style="width: 25px;height: 25px;transform: scale(2.20);margin-right: 0;margin-top: 26px;padding-bottom: 0px;" src="/media/{{dp}}">
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="transform: scale(1.40); margin-top: 30px">
                   <center><li><a class="dropdown-item" href="/profile">Profile</a></li>
                   <li><a class="dropdown-item" href="/about">About</a></li>
                   <li class="dropdown-divider"></li>
                   <li><a class="dropdown-item" href="/signout">Logout</a></li></center>
                  </ul>
                </div>
            </div>
        </div>
    </nav>
<div class="container" style="max-height:646px;">
<div class="row clearfix" style="margin-top: 100px">
    <div class="col-lg-12">
        <div class="card chat-app" style="height:645px;margin-bottom:0px;">
            <div id="plist" class="people-list">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-search"></i></span>
                    </div>
                    <input type="text" class="form-control" placeholder="Search...">
                </div>
                {% for user in users %}  
                <ul class="list-unstyled chat-list mt-2 mb-0">
                <a href="{% url 'chat' request.user.id user.id %}" id="user{{ user.id }}">      
                    <li class="clearfix">
                        
                        <div class="about">
                            <div class="name">{{ user.username }}</div>
                            <div class="status"> <i class="fa fa-circle offline"></i> left 10 hours ago </div>
                        </div>
                    </li>
                </a>
                </ul>
                {% endfor %}
            </div>
            <div class="chat" style="height: 645px; overflow-y: auto;">
                <div class="chat-header clearfix">
                    <div class="row">
                        <div class="col-lg-6">
                            <a href="javascript:void(0);" data-toggle="modal" data-target="#view_info">
                                {% if pro is not None %}
                                <img src="/media/{{pro}}" alt="dp">
                                {% endif %}
                            </a>
                            <div class="chat-about">
                                {% for user in person %}
                                <h6 class="m-b-0">{{ user.username }}</h6>
                                <small>Last seen: 2 hours ago</small>
                                {% endfor %}
                            </div>
                        </div>
                        {% block abc %}
                        
                        {% endblock abc %}
                    </div>
                </div>
                    <div id="board">
                        {% block messages %}

                        {% endblock %}
                    </div>
                <form id="chat-box" class="form-group {% block hide %}hide{% endblock %}" method="post">
                <div class="chat-message clearfix">
                        <div class="input-group mb-0 ">
                        {% csrf_token %}
                        {% block input %}
                        
                        {% endblock input %}
                    </div>
                </div>
            </form>                              
            </div>
        </div>
    </div>
</div>
</div>

<script src="{% static 'js/chat.js' %}"></script>
<script>
    // For receiving
    sender_id = "{{ receiver.id }}";
    receiver_id = "{{ request.user.id }}";

    //For sending
    $(function () {
        scrolltoend();
        $('#chat-box').on('submit', function (event) {
            event.preventDefault();
            var message = $('#id_message');
            send('{{ request.user.username }}', '{{ receiver.username }}', message.val());
            message.val('');
        })
    })
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.js"></script>
</body>
</html>

app/templates/messages.html
{% extends 'direct.html' %}
{% block hide %}{% endblock %}

{% block abc %}
<div class="col-lg-6 hidden-sm text-right">
    <a href="javascript:void(0);" class="btn btn-outline-secondary"><i class="fa fa-camera"></i></a>
    <a href="javascript:void(0);" class="btn btn-outline-primary"><i class="fa fa-image"></i></a>
    <a href="javascript:void(0);" class="btn btn-outline-info"><i class="fa fa-cogs"></i></a>
    <a href="javascript:void(0);" class="btn btn-outline-warning"><i class="fa fa-question"></i></a>
</div>
{% endblock abc %}

{% block messages %}

<div class="chat-history" style="border-bottom: none;">
    <ul class="m-b-0" style="margin-bottom: 0px;">
        {% for message in messages %}
        <li class="clearfix" style="overflow-x: hidden;">
        {% if message.sender == request.user %}
            <div class="message other-message float-right"> {{ message }} </div>
        {% else %}
            <div class="message my-message">{{ message }}</div>                                    
        {% endif %}
        </li>
        {% endfor %}
    </ul>
</div>
<script>
$(function () {
    $('#user{{ receiver.id }}').addClass('active');
    //Call receive function each 1 seconds to check for new messages in the database
    setInterval(receive,1000)
})
</script>
{% endblock %}
{% block input %}
<div class="input-group-prepend">
    <span class="input-group-text"><i class="fa fa-send"></i></span>
</div>
<input id="id_message" name="message" type="text" placeholder="Type your message.." class="form-control">      
{% endblock input %}

app/templates/post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static 'img/Snapify (3).png' %}">
    <title>Minor</title>
    <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://maxcdn.icons8.com/fonts/line-awesome/1.1/css/line-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome5-overrides.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.css">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
</head>
<body>

    <nav class="navbar navbar-light navbar-expand-lg fixed-top shadow-sm" id="mainNav" style="border-color: transparent;border-bottom-color: var(--bs-red);background: var(--bs-light);">
        <div class="container"><a href="/"><img src="{% static 'img/Snapify (1).png' %}" style="width: 150px;height: 55px;" /></a>
            <div class="d-xxl-flex align-items-xxl-center" style="margin: 0px;padding: 0px;margin-right: 0px;transform: scale(0.80);"><a href="/" style=""><i class="la la-home d-xxl-flex align-items-xxl-center" style="margin-right: 100px;transform: scale(2.80);padding: 0px;"></a></i><a href="/index"><i class="fab fa-facebook-messenger d-xxl-flex align-items-xxl-center" style="margin-right: 100px;transform: scale(2);"></i></a><a href="/post"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-plus-square d-xxl-flex align-items-xxl-center" style="margin-right: 100px;transform: scale(2);width: 17px;height: 30px;">
                    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"></path>
                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"></path>
                </svg></a>
                <div class="dropdown" style="margin-right: 50px">
                  <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                   <img class="border rounded-circle d-xxl-flex align-items-xxl-center" style="width: 25px;height: 25px;transform: scale(2.20);margin-right: 0;margin-top: 26px;padding-bottom: 0px;" src="/media/{{pro}}">
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="transform: scale(1.40); margin-top: 30px">
                   <center><li><a class="dropdown-item" href="/profile">Profile</a></li>
                   <li><a class="dropdown-item" href="/about">About</a></li>
                   <li class="dropdown-divider"></li>
                   <li><a class="dropdown-item" href="/signout">Logout</a></li></center>
                  </ul>
                </div>
            </div>
        </div>
    </nav>
    
    <section class="section" style="margin-top:70px;">
      <div class="container" >
      <div class="columns is-mobile has-text-centered">
      <div class="column is-half is-offset-one-quarter">
      <div class="card" style="top-margin:100px">
      <div class="card-content">

      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <h3 class="title is-1">New Post</h3>

        <div class="field">
          <p class="control has-icons-left">
            <label class="label is-medium">Choose your files</label>
            <input type="file" name="file" accept="image/*,video/*" id="dp" required>
          </p>
        </div>

        <div class="field">
          <p class="control has-icons-left">
            <label class="label is-medium">Caption</label>
            <textarea name="desc" cols="40" rows="10" class="input is-medium" id="id_caption"></textarea>
          </p>
        </div>

        <div class="field">
          <p class="control has-icons-left">
            <label class="label is-medium">Tags (add tags, separeted by commas)</label>
            <input type="text" name="tags" class="input is-medium" id="id_tags">
          </p>
        </div>
          
        <div class="field">
          <p class="control">
            <button type="submit" name="action" class="button is-success">
              Create
            </button>
          </p>
        </div>
      </form>
      
      </div>
      </div>
      </div>
      </div>
      </div>
    </section>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.js"></script>
<script src="{% static 'js/script.min.js' %}"></script>
</body>
</html>